services:

  #MYSQL
  mysql:
    image: ${MYSQL_CONTAINER_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      #      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      #      MYSQL_USER: ${MYSQL_USER}
      #      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "${MYSQL_PORT}:3306" # Mappe le port de l'hôte (défini dans .env) au port 3306 du conteneur
    volumes:
      #      - mysql_data:/var/lib/mysql # Persistance des données MySQL
      - $PWD/../sql/databaseSchemaInitFile.sql:/docker-entrypoint-initdb.d/1_databaseSchemaInitFile.sql

  moderation-api:
    build:
      context: ./python
    container_name: moderation-api
    ports:
      - "5000:5000"
    restart: unless-stopped

#volumes:
#  mysql_data: # Définit un volume nommé pour la persistance des données
#    driver: local
